apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    ndkVersion = '29.0.14206865'
//    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "com.e_sppd.rssm"
        minSdkVersion 24
        targetSdkVersion 36
        versionName '5.0'
        multiDexEnabled = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionCode 7
        externalNativeBuild {
            cmake {
                cppFlags ''
            }
        }

        //signingConfig signingConfigs.config
    }
    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
//            signingConfig signingConfigs.config
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'

        jniLibs {
            useLegacyPackaging = false
        }
    }
    productFlavors {
    }
    compileOptions {
    targetCompatibility = 1.8
        sourceCompatibility = 1.8
    }
    namespace = 'com.e_sppd.rssm'
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version = '3.22.1'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.2'

    implementation 'com.google.android.material:material:1.13.0'
    implementation 'me.relex:circleindicator:2.1.6@aar'
    implementation 'com.android.volley:volley:1.2.1'

    implementation 'com.github.bloder:magic:1.0'

    //compile 'com.ebanx:swipe-button:0.4.0'
    testImplementation 'junit:junit:4.13.2'

    //notifikasi
    implementation platform('com.google.firebase:firebase-bom:34.10.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'androidx.multidex:multidex:2.0.1'
    
//    implementation files('libs/httpmime-4.3.6.jar')
//    implementation files('libs/httpcore-4.3.3.jar')

    //circleimage
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    //gif
    implementation 'com.github.bumptech.glide:glide:5.0.5'

    //splashscreen
    implementation 'com.github.ViksaaSkool:AwesomeSplash:v1.0.0'
    //font
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
}
apply plugin: 'com.google.gms.google-services'